# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_application_isprocessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='originalwriter',
            field=models.CharField(default='originlwriter', max_length=40),
        ),
    ]
