# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_application_originalwriter'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='originlwritertyp',
            field=models.CharField(default='N', max_length=10),
            preserve_default=False,
        ),
    ]
