# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_application_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dep',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
    ]
